# Generated by Django 2.0.7 on 2020-06-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('cash_rate_buy', models.CharField(max_length=100)),
                ('cash_rate_sell', models.CharField(max_length=100)),
                ('realtime_rate_buy', models.CharField(max_length=100)),
                ('realtime_rate_sell', models.CharField(max_length=100)),
                ('added_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
